/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:72697cae-8ddf-4629-bfa0-314058eed889",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_XjaLTyZ3n",
    "aws_user_pools_web_client_id": "2t6b0himb59do666a658o3sto2",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://umbj7jmkv5duzcbw3gjwzi5b5a.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-gl7babi3jbbmxevwea3h3rubfy",
    "aws_user_files_s3_bucket": "redditclone0268dbc7da584167bae51857834450fe22753-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
